# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python37:
      python.version: '3.7'

# parameters:
# - name: methods
#   type: string
#   default: staple
#   values:
#   - staple
#   - itkvoting
#   - majorityvoting
#   - simple

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install .
  displayName: 'Install dependencies'

# - ${{ each method in parameters.methods }}:
#   - script: |
#     python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_${{ method }}.nii.gz -classes 0,1,2,4 -method ${{ method }}
#     python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_${{ method }}.nii.gz', './data/test_${{ method }}.nii.gz'))) else print('pass')"

- bash: |
    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_staple.nii.gz -classes 0,1,2,4 -method staple
    error_code=$?
    if [[ $error_code -eq 0 ]]; then
        exit 1
    fi
    exit 0
    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_itkvoting.nii.gz -classes 0,1,2,4 -method itkvoting
    error_code=$?
    if [[ $error_code -eq 0 ]]; then
        exit 1
    fi
    exit 0
    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_majorityvoting.nii.gz -classes 0,1,2,4 -method majorityvoting
    error_code=$?
    if [[ $error_code -eq 0 ]]; then
        exit 1
    fi
    exit 0
    python fusion_run -inputs ./data/unet.nii.gz,./data/resunet.nii.gz -output ./data/test_simple.nii.gz -classes 0,1,2,4 -method simple
    error_code=$?
    if [[ $error_code -eq 0 ]]; then
        exit 1
    fi
    exit 0
  displayName: 'Run through all options'
  
- bash: |
    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_staple.nii.gz', './data/test_staple.nii.gz'))) else print('pass')"
    error_code=$?
    if [[ $error_code -eq 0 ]]; then
        exit 1
    fi
    exit 0
    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_itkvoting.nii.gz', './data/test_itkvoting.nii.gz'))) else print('pass')"
    error_code=$?
    if [[ $error_code -eq 0 ]]; then
        exit 1
    fi
    exit 0
    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_majorityvoting.nii.gz', './data/test_majorityvoting.nii.gz'))) else print('pass')"
    error_code=$?
    if [[ $error_code -eq 0 ]]; then
        exit 1
    fi
    exit 0
    python -c "from Methods.itkUtils import *; sys.exit('fail') if(not (imageComparision('./data/baseline_simple.nii.gz', './data/test_simple.nii.gz'))) else print('pass')"
    error_code=$?
    if [[ $error_code -eq 0 ]]; then
        exit 1
    fi
    exit 0
  displayName: 'Compare generated results'
    