#!usr/bin/env python
# -*- coding: utf-8 -*-

import os
import argparse
import sys
from pathlib import Path
import pkg_resources
from datetime import date

def main():
    copyrightMessage = 'Contact: software@cbica.upenn.edu\n\n' + 'This program is NOT FDA/CE approved and NOT intended for clinical use.\nCopyright (c) ' + str(date.today().year) + ' University of Pennsylvania. All rights reserved.' 
    parser = argparse.ArgumentParser(prog='LabelFusion', formatter_class=argparse.RawTextHelpFormatter, description = "Fusion of different labels together.\n\n" + copyrightMessage)

if __name__ == '__main__':
    main()
